language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO='Django<=1.4' PYSCOPG2='psycopg2==2.4.1' # see django issue #16250
  - DJANGO='Django<=1.5' PYSCOPG2='psycopg2'
  - DJANGO='Django<=1.6' PYSCOPG2='psycopg2'

install:
  - pip install -q $PYSCOPG2 --use-mirrors
  - pip install -q $DJANGO --use-mirrors
  - pip install -q IPy --use-mirrors
  - pip install . --use-mirrors

before_script:
  - psql -c 'create database netfields;' -U postgres

script: "./manage.py test"
