---
# 
# Install Dell utility OMSA on Debian servers
#
- hosts: '{{ Hosts }}'
  vars_files:
    - vars/DefaultVars.yml
  handlers:
    - include: handlers/Handlers.yml
  tasks:
    - include_vars: vars/DebianVars.yml
      when: (ansible_distribution == "Debian")
    - include_vars: vars/CentosVars.yml
      when: (ansible_distribution == "CentOS")

    - name: Add Dell repository 
      sudo: yes
      shell: /bin/echo "deb http://linux.dell.com/repo/community/deb/latest /" >> /etc/apt/sources.list.d/dell.list

    - name: Add Dell repo keys
      sudo: yes
      apt_key: url=hkp://pool.sks-keyservers.net:80 id=1285491434D8786F state=present
 
    - name: Install Dell utils
      sudo: yes
      apt: pkg='{{item}}' update_cache=yes force=yes install_recommends=yes
      with_items:
        - srvadmin-all
      notify:
        - restart dataeng
        - restart dsm_om_connsvc

    - name: Check dell.list exist
      stat: path=/etc/apt/sources.list.d/dell.list
      register: dell_stat

    - name: Disable Dell repository
      sudo: yes
      command: mv /etc/apt/sources.list.d/dell.list /etc/apt/sources.list.d/dell.list.disabled
      when: dell_stat.stat.exists
