---
# 
# Install Dell utility OMSA on Debian servers
#
- hosts: '{{ Hosts }}'
  vars_files:
    - vars/DefaultVars.yml
  handlers:
    - include: handlers/Handlers.yml
  tasks:
    - include_vars: vars/DebianVars.yml
      when: (ansible_distribution == "Debian")
    - include_vars: vars/CentosVars.yml
      when: (ansible_distribution == "CentOS")

    - name: Add Dell repository 
      sudo: yes
      shell: /bin/echo "deb http://linux.dell.com/repo/community/deb/latest /" >> /etc/apt/sources.list.d/dell.list

#    - name: add Dell apt-key
#      sudo: yes
#      apt_key: keyserver=pool.sks-keyservers.net id=1285491434D8786F

    - name: Download libssl package
      sudo: yes
      get_url: url=http://snapshot.debian.org/archive/debian/20110406T213352Z/pool/main/o/openssl098/libssl0.9.8_0.9.8o-7_amd64.deb  
        dest=/root/libssl0.9.8_0.9.8o-7_amd64.deb 
      environment:
        http_proxy: http://www-cache.ujf-grenoble.fr:3128

    - name: Install libssl package
      sudo: yes
      apt: deb=/root/libssl0.9.8_0.9.8o-7_amd64.deb

    - name: Install Dell utils
      sudo: yes
      apt: pkg='{{item}}' update_cache=yes force=yes
      with_items:
        - srvadmin-base
        - srvadmin-rac5
        - srvadmin-idrac7
        - srvadmin-webserver
        - srvadmin-storageservices
      notify:
        - restart dataeng
        - restart dsm_om_connsvc

    - name: Check dell.list exist
      stat: path=/etc/apt/sources.list.d/dell.list
      register: dell_stat

    - name: Disable Dell repository
      sudo: yes
      command: mv /etc/apt/sources.list.d/dell.list /etc/apt/sources.list.d/dell.list.disabled
      when: dell_stat.stat.exists
