---
# 
# Manage repository list
#

- hosts: dmz98
  tasks:

   - name: "Backup sources.list on debian flavored systems"
     sudo: yes
     command: /bin/mv sources.list sources.list.orig chdir=/etc/apt

   - name: "Manage main repository on debian 7 flavored systems"
     sudo: yes
     shell: /bin/echo -e "deb http://ftp.fr.debian.org/debian/ wheezy main contrib non-free\ndeb http://ftp.fr.debian.org/debian/ wheezy-updates main contrib non-free" > sources.list chdir=/etc/apt
     when: (ansible_distribution == "Debian" and ansible_distribution_major_version == "7")

   - name: "Manage main repository on debian 8 flavored systems"
     sudo: yes
     shell: /bin/echo -e "deb http://ftp.fr.debian.org/debian/ jessie main contrib non-free\ndeb http://ftp.fr.debian.org/debian/ jessie-updates main contrib non-free" > sources.list chdir=/etc/apt
     when: (ansible_distribution == "Debian" and ansible_distribution_major_version == "8")

   - name: "Manage security repository on debian 7 flavored systems"
     sudo: yes
     shell: /bin/echo "deb http://security.debian.org/ wheezy/updates main contrib non-free" > security.list chdir=/etc/apt/sources.list.d
     when: (ansible_distribution == "Debian" and ansible_distribution_major_version == "7")

   - name: "Manage security repository on debian 8 flavored systems"
     sudo: yes
     shell: /bin/echo "deb http://security.debian.org/ jessie/updates main contrib non-free" > security.list chdir=/etc/apt/sources.list.d
     when: (ansible_distribution == "Debian" and ansible_distribution_major_version == "8")

   - name: "Manage Megacli repository on debian 7 flavored systems"
     sudo: yes
     shell: /bin/echo "deb http://hwraid.le-vert.net/debian wheezy main" > megacli.list.disabled chdir=/etc/apt/sources.list.d
     when: (ansible_distribution == "Debian" and ansible_distribution_major_version == "7")

   - name: "Manage Megacli repository on debian 8 flavored systems"
     sudo: yes
     shell: /bin/echo "deb http://hwraid.le-vert.net/debian jessie main" > megacli.list.disabled chdir=/etc/apt/sources.list.d
     when: (ansible_distribution == "Debian" and ansible_distribution_major_version == "8")

   - name: "Manage Dell repository"
     sudo: yes
     shell: /bin/echo "deb http://linux.dell.com/repo/community/deb/latest /" > dell.list.disabled chdir=/etc/apt/sources.list.d 

   - name: "Manage Zabbix repository on debian 7 flavored systems"
     sudo: yes
     shell: echo -e "deb http://repo.zabbix.com/zabbix/2.4/debian wheezy main\ndeb-src http://repo.zabbix.com/zabbix/2.4/debian wheezy main" > zabbix.list.disabled chdir=/etc/apt/sources.list.d
     when: (ansible_distribution == "Debian" and ansible_distribution_major_version == "7")

   - name: "Manage Zabbix repository on debian 8 flavored systems"
     sudo: yes
     shell: echo -e "deb http://repo.zabbix.com/zabbix/2.4/debian jessie main\ndeb-src http://repo.zabbix.com/zabbix/2.4/debian jessie main" > zabbix.list.disabled chdir=/etc/apt/sources.list.d
     when: (ansible_distribution == "Debian" and ansible_distribution_major_version == "8")
